"""empty message

Revision ID: 2929eb51a137
Revises: 73ca462ebaa2
Create Date: 2016-10-03 23:53:14.494847

"""

# revision identifiers, used by Alembic.
revision = '2929eb51a137'
down_revision = '73ca462ebaa2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    ### end Alembic commands ###
