"""empty message

Revision ID: 55f26e7864a0
Revises: 1bc3202af6f8
Create Date: 2016-09-22 16:28:31.646337

"""

# revision identifiers, used by Alembic.
revision = '55f26e7864a0'
down_revision = '1bc3202af6f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    ### end Alembic commands ###
