"""empty message

Revision ID: 5cb7ff3456e2
Revises: None
Create Date: 2016-10-10 21:19:46.514827

"""

# revision identifiers, used by Alembic.
revision = '5cb7ff3456e2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postpic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postpic')
    ### end Alembic commands ###
