"""empty message

Revision ID: 75234f9195a4
Revises: None
Create Date: 2016-08-18 13:49:21.606330

"""

# revision identifiers, used by Alembic.
revision = '75234f9195a4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    ### end Alembic commands ###
